test:
  adapter: postgresql
  encoding: unicode
  database: bch_bluetooth_test_db
  pool: 2
  username: postgres 
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  database: bch_bluetooth_db
  pool: 2
  username: postgres 
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>